dataset:
  name: "stable icospheres"
  raw_train_data_dir: "data/raw/ldraw_models/primitives stable/icosphere/train/"
  raw_test_data_dir: "data/raw/ldraw_models/primitives stable/icosphere/test/"
  rotations: [0, 1]
  base_path: "data/processed/primitives stable/icosphere"

  subsets:
    subset1:
      iteration:
        channel_shape: [30, 15, 30]
        group_shape: [5, 5, 5]
        shape_top_ext: 2
        height: 3
      data:
        train_path: "data/processed/primitives stable/icosphere/train_set1.dataset"
        test_path: "data/processed/primitives stable/icosphere/test_set1.dataset"
      bricks: ["3004", "3005"]
  misc:
    seed: 42