version: 2.1

# Define the jobs we want to run for this project
jobs:
  test:
    docker:
      - image: cimg/python:3.8.0
    steps:
      - checkout
      - run: python3 --version
      - run:
          name: upgrade pip
          command: pip install --upgrade pip
      - run:
          name: create virtual environemnt
          command: |
            python3 -m venv venv
            . venv/bin/activate
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: install package
          command: pip install -e .
      - run:
          name: unit tests
          command: |
            python3 -m unittest discover -s tests/unit/
      - run:
          name: integration tests
          command: |
            python3 -m unittest discover -s tests/integration/

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - test