version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/python:3.8.0
    steps:
      - checkout
      - run: echo "this is the build job"
      - run:
          name: install python3.10-venv
          command: |
            sudo apt update
            sudo apt upgrade
            sudo apt install python3.10-venv
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test