version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/python:3.8.0
    steps:
      - checkout
      - run: python3 --version
      - run:
          name: upgrade pip
          command: pip install --upgrade pip
      - run:
          name: create virtual environemnt
          command: |
            python3 -m venv venv
            . venv/bin/activate
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
  test:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test