model:
  name: PrimNet8
  type: cnn
  num_classes: 6
  input_shape: [30, 15, 30]

  bricks: ["3004", "3005"]
  labels:
    "None":
      0: 0
    "3004":
      0: 1
      90: 2
      180: 3
      270: 4
    "3005":
      0: 5
      90: 5
      180: 5
      270: 5

iteration:
  channel_shape: [30, 15, 30]
  group_shape: [5, 5, 5]
  shape_top_ext: 2
  height: 3