model:
  name: LegoNet
  type: cnn
  hidden_dim: 128
  num_classes: 10
  input_shape: [30, 15, 30]

  bricks: ["3004", "3005", "54200"]
  labels:
    "None":
      0: 0
    "3004":
      0: 1
      90: 2
      180: 3
      270: 4
    "3005":
      0: 5
      90: 5
      180: 5
      270: 5
    "54200":
      0: 6
      90: 7
      180: 8
      270: 9

iteration:
  channel_shape: [30, 15, 30]
  group_shape: [5, 5, 5]
  shape_top_ext: 2
  height: 3