model:
  name: LegoNet4
  config_path: "configs/models/arch1.model.yaml"
  checkpoint: "models/classification/arch1v0.pth"

data:
  train_path: ["data/processed/smountain2/train_set1.dataset", data/processed/tower1/train_set1.dataset, data/processed/point/train_set1.dataset, data/processed/pillarsnwalls/train_set1.dataset]
  test_path: ["data/processed/smountain2/test_set1.dataset", data/processed/tower1/test_set1.dataset, data/processed/point/test_set1.dataset, data/processed/pillarsnwalls/test_set1.dataset]

training:
  epochs: 30 # 19
  batch_size: 8
  lr: 0.001
  optimizer: adam
  save_path: "models/classification/arch1v1.pth"

misc:
  seed: 42
  device: "cuda"