model:
  name: LegoNet3
  config_path: "configs/models/smountain5.model.yaml"
  checkpoint: "models/classification/smountain5v0.pth"

data:
  train_path: ["data/processed/smountain2/train_set1.dataset"]
  test_path: ["data/processed/smountain2/test_set1.dataset"]

training:
  epochs: 13 # 19
  batch_size: 8
  lr: 0.001
  optimizer: adam
  save_path: "models/classification/smountain5v1.pth"

misc:
  seed: 42
  device: "cuda"