legolization:
  name: tower
  models:
    model1:
      config_path: "configs/models/buildingsnet1.model.yaml"
      model_path: "models/classification/tower1v1.pth"
    model2:
      config_path: "configs/models/buildingsnet2.model.yaml"
      model_path: "models/classification/tower2v1.pth"