model:
  name: PrimNet1
  config_path: "configs/models/primnet1.model.yaml"
  checkpoint: "models/classification/primnet1v0.pth"

data:
  train_path: [data/processed/primitives unstable/cone/train_set1.dataset]
  test_path: [data/processed/primitives unstable/cone/test_set1.dataset]

training:
  epochs: 4 # 19
  batch_size: 8
  lr: 0.001
  optimizer: adam
  save_path: "models/classification/unst_conenet1v1.pth"

misc:
  seed: 42
  device: "cuda"