model:
  name: BuildingsNet1
  config_path: "configs/models/buildingsnet1.model.yaml"
  checkpoint: "models/classification/buildingsnet1v0.pth"

data:
  train_path: [data/processed/mini-buildings/datasets/feeder/train_set1.dataset]
  test_path: [data/processed/mini-buildings/datasets/feeder/test_set1.dataset]

training:
  epochs: 15
  batch_size: 8
  lr: 0.0001
  optimizer: adam
  save_path: "models/classification/mini-buildings/feeder1v1.pth"

misc:
  seed: 42
  device: "cuda"