
name: Python package

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Create venv if doesn't exist
      run: sh .github/create_venv.sh
    - name: Lint with flake8
      run: |
        source $HOME/.local/nelegolizer-venv/bin/activate
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        source $HOME/.local/nelegolizer-venv/bin/activate
        pytest
